pipeline:
  generate-tags:
    image: quay.io/natlibfi/drone-gen-tags
  docker:
    image: plugins/docker
    registry: quay.io
    repo: quay.io/natlibfi/portainer-update-stack
    secrets:
    - docker_username
    - docker_password
